x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: docker/airflow/Dockerfile
  environment:
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
      postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@${AIRFLOW_POSTGRES_HOST}:${AIRFLOW_POSTGRES_PORT}/${AIRFLOW_POSTGRES_DB}
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__DEFAULT_TIMEZONE: UTC
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: >-
      ${AIRFLOW_ADMIN_USERNAME}:admin
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: >-
      /opt/airflow/config/simple_auth_manager_passwords.json
    PYTHONPATH: /opt/airflow/project
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://airflow-logs"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "minio_s3_conn"
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - .:/opt/airflow/project
    - airflow_config:/opt/airflow/config
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    command: ["sleep", "infinity"]
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - cybersport_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9002:9000"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - cybersport_clickhouse_data:/var/lib/clickhouse
    depends_on:
      - postgres
  airflow-postgres:
    image: postgres:17-alpine
    container_name: airflow-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AIRFLOW_POSTGRES_USER} -d ${AIRFLOW_POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    restart: "no"
    user: root
    depends_on:
      airflow-postgres:
        condition: service_healthy
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p /opt/airflow/config
        cat > /opt/airflow/config/simple_auth_manager_passwords.json <<EOF
        {
          "${AIRFLOW_ADMIN_USERNAME}": "${AIRFLOW_ADMIN_PASSWORD}"
        }
        EOF
        chown airflow:root \
          /opt/airflow/config/simple_auth_manager_passwords.json
        chmod 600 \
          /opt/airflow/config/simple_auth_manager_passwords.json
        su airflow -c "airflow db migrate"
  airflow-api-server:
    <<: *airflow-common
    container_name: airflow-api-server
    hostname: airflow_api_server
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      minio:
        condition: service_started
      clickhouse:
        condition: service_started
    ports:
      - "8080:8080"
    env_file:
      - .env
    command:
      - airflow
      - api-server
      - --port
      - "8080"
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    hostname: airflow_scheduler
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    command:
      - airflow
      - scheduler
  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow-dag-processor
    hostname: airflow_dag_processor
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    command:
      - airflow
      - dag-processor
  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    hostname: airflow_triggerer
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    command:
      - airflow
      - triggerer
volumes:
  cybersport_postgres_data:
  cybersport_clickhouse_data:
  airflow_postgres_data:
  airflow_config: