import os
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.getenv('BASE_URL')

EVENTS_SOURCE_URL = os.getenv('EVENTS_SOURCE_URL')
EVENTS_LIMIT = int(os.getenv('EVENTS_LIMIT', 5))

MINIO_HOST = os.getenv('MINIO_HOST')
MINIO_USER = os.getenv('MINIO_USER')
MINIO_PASSWORD = os.getenv('MINIO_PASSWORD')

MINIO_EVENTS_BUCKET_NAME = os.getenv('MINIO_EVENTS_BUCKET_NAME')
MINIO_MATCHES_BUCKET_NAME = os.getenv('MINIO_MATCHES_BUCKET_NAME')
MINIO_STATISTICS_BUCKET_NAME = os.getenv('MINIO_STATISTICS_BUCKET_NAME')

HTTP_TIMEOUT_SECONDS = int(os.getenv('HTTP_TIMEOUT_SECONDS', 30))

SENTRY_DSN = os.getenv('SENTRY_DSN')
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', 0.0))

POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_DB = os.getenv('POSTGRES_DB')