"""remove_title_from_match

Revision ID: 1fe7772424c5
Revises: 2f2e55a0adce
Create Date: 2026-09-10 04:10:50.280116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe7772424c5'
down_revision: Union[str, Sequence[str], None] = '2f2e55a0adce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
