"""add_unique_match_map_to_match_maps

Revision ID: 291eaaefd17e
Revises: 9cc2b0682660
Create Date: 2026-09-15 15:03:40.247446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291eaaefd17e'
down_revision: Union[str, Sequence[str], None] = '9cc2b0682660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_maps_match_map', 'match_maps', ['match_id', 'map_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_maps_match_map', 'match_maps', type_='unique')
    # ### end Alembic commands ###
