"""add_created_at_to_matches_and_statistics

Revision ID: 2a7287bbdbf9
Revises: d858ff93b844
Create Date: 2026-09-12 05:28:01.586651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7287bbdbf9'
down_revision: Union[str, Sequence[str], None] = 'd858ff93b844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('statistics', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'created_at')
    op.drop_column('matches', 'created_at')
    # ### end Alembic commands ###
