"""change_external_id_to_slug_in_teams

Revision ID: 86839e58366e
Revises: 435b9f51372b
Create Date: 2026-09-12 06:34:04.212436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86839e58366e'
down_revision: Union[str, Sequence[str], None] = '435b9f51372b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('slug', sa.Text(), nullable=False))
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=False)
    op.drop_column('teams', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('external_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.drop_column('teams', 'slug')
    # ### end Alembic commands ###
