"""add_unique_team_player_match_id_to_statistics

Revision ID: 9cc2b0682660
Revises: 20bf31f9e0dc
Create Date: 2026-09-15 10:44:05.236412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc2b0682660'
down_revision: Union[str, Sequence[str], None] = '20bf31f9e0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_statistics_match_player_team', 'statistics', ['match_id', 'player_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_statistics_match_player_team', 'statistics', type_='unique')
    # ### end Alembic commands ###
