"""remove_team_ids_from_match_maps

Revision ID: da158f481ca1
Revises: 03aedd4e2266
Create Date: 2026-09-13 04:24:10.300489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da158f481ca1'
down_revision: Union[str, Sequence[str], None] = '03aedd4e2266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_maps_team_first_id'), table_name='match_maps')
    op.drop_index(op.f('ix_match_maps_team_second_id'), table_name='match_maps')
    op.drop_constraint(op.f('match_maps_team_first_id_fkey'), 'match_maps', type_='foreignkey')
    op.drop_constraint(op.f('match_maps_team_second_id_fkey'), 'match_maps', type_='foreignkey')
    op.drop_column('match_maps', 'team_first_id')
    op.drop_column('match_maps', 'team_second_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_maps', sa.Column('team_second_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_maps', sa.Column('team_first_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('match_maps_team_second_id_fkey'), 'match_maps', 'teams', ['team_second_id'], ['id'])
    op.create_foreign_key(op.f('match_maps_team_first_id_fkey'), 'match_maps', 'teams', ['team_first_id'], ['id'])
    op.create_index(op.f('ix_match_maps_team_second_id'), 'match_maps', ['team_second_id'], unique=False)
    op.create_index(op.f('ix_match_maps_team_first_id'), 'match_maps', ['team_first_id'], unique=False)
    # ### end Alembic commands ###
