"""set_statistics_rating_nullable

Revision ID: 03aedd4e2266
Revises: 86839e58366e
Create Date: 2026-09-13 03:30:12.027917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03aedd4e2266'
down_revision: Union[str, Sequence[str], None] = '86839e58366e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False)
    # ### end Alembic commands ###
