"""add_slug_to_events

Revision ID: 2f2e55a0adce
Revises: 7825844eeb32
Create Date: 2026-09-09 06:41:01.239181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2e55a0adce'
down_revision: Union[str, Sequence[str], None] = '7825844eeb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('slug', sa.Text(), nullable=False))
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_column('events', 'slug')
    # ### end Alembic commands ###
