"""add_teams_table

Revision ID: 435b9f51372b
Revises: 2a7287bbdbf9
Create Date: 2026-09-12 06:20:38.323685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435b9f51372b'
down_revision: Union[str, Sequence[str], None] = '2a7287bbdbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.add_column('match_maps', sa.Column('team_first_id', sa.Integer(), nullable=False))
    op.add_column('match_maps', sa.Column('team_second_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_match_maps_team_first_id'), 'match_maps', ['team_first_id'], unique=False)
    op.create_index(op.f('ix_match_maps_team_second_id'), 'match_maps', ['team_second_id'], unique=False)
    op.create_foreign_key(None, 'match_maps', 'teams', ['team_first_id'], ['id'])
    op.create_foreign_key(None, 'match_maps', 'teams', ['team_second_id'], ['id'])
    op.drop_column('match_maps', 'team2')
    op.drop_column('match_maps', 'team1')
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    op.add_column('statistics', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_statistics_team_id'), 'statistics', ['team_id'], unique=False)
    op.create_foreign_key(None, 'statistics', 'teams', ['team_id'], ['id'])
    op.drop_column('statistics', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'statistics', type_='foreignkey')
    op.drop_index(op.f('ix_statistics_team_id'), table_name='statistics')
    op.drop_column('statistics', 'team_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_column('players', 'team_id')
    op.add_column('match_maps', sa.Column('team1', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('match_maps', sa.Column('team2', sa.TEXT(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'match_maps', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'match_maps', type_='foreignkey')
    op.drop_index(op.f('ix_match_maps_team_second_id'), table_name='match_maps')
    op.drop_index(op.f('ix_match_maps_team_first_id'), table_name='match_maps')
    op.drop_column('match_maps', 'team_second_id')
    op.drop_column('match_maps', 'team_first_id')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
