"""create match_maps table

Revision ID: c57a2f4c5680
Revises: f8d98317aba0
Create Date: 2026-09-07 06:16:33.480567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57a2f4c5680'
down_revision: Union[str, Sequence[str], None] = 'f8d98317aba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=50), nullable=False),
    sa.Column('team1', sa.Text(), nullable=False),
    sa.Column('team2', sa.Text(), nullable=False),
    sa.Column('score', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_maps_match_id'), 'match_maps', ['match_id'], unique=False)
    op.drop_index(op.f('ix_maps_match_id'), table_name='maps')
    op.drop_table('maps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('map_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('team1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('maps_match_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('maps_pkey'))
    )
    op.create_index(op.f('ix_maps_match_id'), 'maps', ['match_id'], unique=False)
    op.drop_index(op.f('ix_match_maps_match_id'), table_name='match_maps')
    op.drop_table('match_maps')
    # ### end Alembic commands ###
