"""add_maps

Revision ID: f3a2967c160d
Revises: da158f481ca1
Create Date: 2026-09-13 04:33:12.423732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a2967c160d'
down_revision: Union[str, Sequence[str], None] = 'da158f481ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('match_maps', sa.Column('map_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_match_maps_map_id'), 'match_maps', ['map_id'], unique=False)
    op.create_foreign_key(None, 'match_maps', 'maps', ['map_id'], ['id'])
    op.drop_column('match_maps', 'map_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_maps', sa.Column('map_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'match_maps', type_='foreignkey')
    op.drop_index(op.f('ix_match_maps_map_id'), table_name='match_maps')
    op.drop_column('match_maps', 'map_id')
    op.drop_table('maps')
    # ### end Alembic commands ###
