"""create matches table

Revision ID: f8d98317aba0
Revises: d7a9687846a1
Create Date: 2026-09-06 06:17:40.160762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d98317aba0'
down_revision: Union[str, Sequence[str], None] = 'd7a9687846a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('team1', sa.Text(), nullable=False),
    sa.Column('team2', sa.Text(), nullable=False),
    sa.Column('score', sa.String(length=10), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_event_id'), 'matches', ['event_id'], unique=False)
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=50), nullable=False),
    sa.Column('team1', sa.Text(), nullable=False),
    sa.Column('team2', sa.Text(), nullable=False),
    sa.Column('score', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_match_id'), 'maps', ['match_id'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_match_id'), 'statistics', ['match_id'], unique=False)
    op.create_index(op.f('ix_statistics_player_id'), 'statistics', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_player_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_match_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_maps_match_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_event_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('players')
    # ### end Alembic commands ###
